<script lang="ts">
	import { generateId } from '@melt-ui/svelte/internal/helpers'
	import { accordionCtx } from './Accordion.svelte'
	import { browser } from '$app/environment'
	import { slide } from 'svelte/transition'
	import { melt } from '@melt-ui/svelte'
	import type { Snippet } from 'svelte'

	const {
		elements: { item, trigger, content },
		helpers: { isSelected },
		states: { value },
	} = accordionCtx.get()

	let {
		open = false,
		classInactive = '',
		disabled = false,
		header,
		children,
	}: {
		open?: boolean
		classInactive?: string
		disabled?: boolean
		header?: Snippet
		children?: Snippet
	} = $props()

	const id = generateId()
	const isHtmlOnly = !browser

	$effect(() => {
		if (open) {
			value.set(id)
		}
	})
</script>

{#if isHtmlOnly}
	<details {open} class={disabled ? classInactive : ''}>
		<!-- svelte-ignore a11y_no_noninteractive_tabindex - False positive -->
		<summary
			class="flex items-center justify-between gap-3 w-full p-5 font-medium rtl:text-right
			border border-gray-700 text-gray-400 hover:bg-gray-800 focus:outline-2 focus:outline-svelte focus:outline"
			tabindex={disabled ? -1 : undefined}>
			{@render header?.()}
		</summary>

		<div
			class="p-5 border border-gray-200 dark:border-gray-700 dark:bg-gray-900">
			<div class="px-5 py-4">
				{@render children?.()}
			</div>
		</div>
	</details>
{:else}
	<div
		use:melt={$item({ value: id, disabled })}
		class={disabled ? classInactive : ''}>
		<button
			use:melt={$trigger({ value: id, disabled })}
			class="flex items-center justify-between gap-3 w-full p-5 font-medium rtl:text-right
			border border-gray-700 text-gray-400 hover:bg-gray-800 focus:outline-2 focus:outline-svelte focus:outline">
			{@render header?.()}

			<!-- ! This file is automatically generated, please don't edit it directly. -->

			<svg
				class="transition-transform duration-300"
				class:rotate-180={$isSelected(id)}
				width="24"
				height="24"
				viewBox="0 0 24 24"
				fill="none"
				xmlns="http://www.w3.org/2000/svg">
				<g class="oi-chevron-down">
					<path
						class="oi-incomplete-triangle stroke-gray-400"
						d="M18 10L12 16L6 10"
						stroke-width="2"
						stroke-miterlimit="10"
						stroke-linecap="round"
						stroke-linejoin="round" />
				</g>
			</svg>
		</button>

		{#if $isSelected(id)}
			<div
				class="p-5 border border-gray-200 dark:border-gray-700 dark:bg-gray-900"
				use:melt={$content(id)}
				transition:slide>
				<div class="px-5 py-4">
					{@render children?.()}
				</div>
			</div>
		{/if}
	</div>
{/if}

<style lang="postcss">
	details {
		&:first-child summary {
			@apply rounded-t-xl;
		}

		&:not(:last-child) summary {
			@apply border-b-0;
		}

		&:not(:last-child) [data-melt-accordion-content] {
			@apply border-b-0;
		}

		&:last-child [data-melt-accordion-content] {
			@apply border-t-0;
		}

		summary {
			list-style: none;
			&::-webkit-details-marker {
				display: none;
			}
		}
	}

	*:is([data-melt-accordion-item]) {
		&:first-child button {
			@apply rounded-t-xl;
		}

		&:not(:last-child) button {
			@apply border-b-0;
		}

		&:not(:last-child) [data-melt-accordion-content] {
			@apply border-b-0;
		}

		&:last-child [data-melt-accordion-content] {
			@apply border-t-0;
		}
	}
</style>
